### PR TITLE
add EGG space

### PR DESCRIPTION
**Pull request by bitbd83**
**Add space for ...**  
  
Etherscan: https://etherscan.io/address/0x2b7018Fca0eccfBc738828e1E8f1C7038EBBCaa8
CoinGecko: https://www.coingecko.com/en/coins/...  
Website: https://eggy.finance
Twitter: https://twitter.com/EggyFinance

### CODE REVIEW

**Comment by e-asia** [comment]
The images file size should not exceed 50KB. Please reduce their weight.

**Review by bitbd83 — COMMENTED** [review]
change logo weight

**Comment by bitbd83** [comment]
logo updated.

**Review by bitbd83 — COMMENTED** [review]
all reviewed.

**Comment by bitbd83** [comment]
> The images file size should not exceed 50KB. Please reduce their weight.

It has changes.

**Review by e-asia — APPROVED** [review]

**Pull request merged**
