### PR TITLE
Add SELF space II - fix color code.

### PR DESCRIPTION
**Pull request by dAAAb**
https://github.com/bonustrack/snapshot-spaces/commit/6bb0f9aa1fb59f6b160f1257905cdc0cb8fb2035
thanks!

### CODE REVIEW

**Review by e-asia — APPROVED** [review]

**Comment by bonustrack** [comment]
@dAAAb Can you use a logo and space image with a size less than 50kb?

**Review by dAAAb — COMMENTED** [review]
- Add SELF space
- fix scss color code
- minimize PNG logo/space image size

**Comment by dAAAb** [comment]
> @dAAAb Can you use a logo and space image with a size less than 50kb and resolve conflicts?

Thank! I already replace png file with smaller one.
But it seems only those with write access to this repository can resolve conflicts?
[[screenshot]](https://www.dropbox.com/s/jgt6ok6g09rourq/resolve.png?dl=0)

**Comment by bonustrack** [comment]
@dAAAb You will need to do it from your IDE / console.

**Comment by dAAAb** [comment]
> @dAAAb You will need to do it from your IDE / console.

@bonustrack , thanks for your patience. 
It seems able to be merged, right? 
Thank you very much!

**Comment by bonustrack** [comment]
@dAAAb Yep!

**Pull request merged**
