### PR TITLE
Dollar Protocol Merge Round 2

### PR DESCRIPTION
**Pull request by satoshinate**
@bonustrack and @e-asia - updated to the correct repo.

### CODE REVIEW

**Review by e-asia — APPROVED** [review]

**Comment by satoshinate** [comment]
thanks! will this workspace have a unique url?

**Comment by e-asia** [comment]
> thanks! will this workspace have a unique url?

Yes, the url is equal to the key value of the index.json file, your url will be /#/dollarProtocol in your case.

**Comment by e-asia** [comment]
@satoshinate we are going to modify all the urls in lowercase, so you should modify the value of the key by something like dollar-protocol

**Comment by satoshinate** [comment]
done

**Review by e-asia — APPROVED** [review]

**Comment by satoshinate** [comment]
@e-asia any timeline on this being merged in? would love to start using this with our community

**Comment by e-asia** [comment]
@satoshinate This will be done in the next few hours

**Comment by bonustrack** [comment]
@satoshinate The folder name and the space key must be the same. Can you change the folder to "dollar-protocol"?

**Comment by satoshinate** [comment]
@bonustrack done

**Comment by satoshinate** [comment]
Any update on merge? Really excited for this

**Pull request merged**
